Repository stfc/fparser, pull requests merged in 2019-11, with the labels that each got.

#208 Fix for utf characters in Fortran statements (for 207) and use `exc.value` in tests
  src/fparser/common/base_classes.py
  src/fparser/common/readfortran.py
  src/fparser/common/splitline.py
  src/fparser/common/tests/test_readfortran.py
  src/fparser/common/tests/test_utils.py
  src/fparser/common/tests/utf_in_code.f90
  src/fparser/one/statements.py
  src/fparser/one/tests/test_block_stmts.py
  src/fparser/one/tests/test_parser.py
  src/fparser/one/tests/test_select.py
  src/fparser/scripts/fparser2.py
  src/fparser/two/Fortran2003.py
  src/fparser/two/tests/fortran2003/test_char_literal_constant_r427.py
  src/fparser/two/tests/fortran2003/test_control_edit_descriptor_r1011.py
  src/fparser/two/tests/fortran2003/test_cray_pointee_array_spec.py
  src/fparser/two/tests/fortran2003/test_cray_pointee_decl.py
  src/fparser/two/tests/fortran2003/test_cray_pointer_decl.py
  src/fparser/two/tests/fortran2003/test_cray_pointer_stmt.py
  src/fparser/two/tests/fortran2003/test_data_edit_desc_c1002.py
  src/fparser/two/tests/fortran2003/test_defined_operator_r311.py
  src/fparser/two/tests/fortran2003/test_defined_operators_r703_r723.py
  src/fparser/two/tests/fortran2003/test_derived_type_stmt_r430.py
  src/fparser/two/tests/fortran2003/test_extended_intrinsic_op_r312.py
  src/fparser/two/tests/fortran2003/test_forall_header_r754.py
  src/fparser/two/tests/fortran2003/test_forall_stmt_r759.py
  src/fparser/two/tests/fortran2003/test_format_item_c1002.py
  src/fparser/two/tests/fortran2003/test_format_item_list.py
  src/fparser/two/tests/fortran2003/test_format_item_r1003.py
  src/fparser/two/tests/fortran2003/test_hollerith_item.py
  src/fparser/two/tests/fortran2003/test_include_statement.py
  src/fparser/two/tests/fortran2003/test_intrinsics.py
  src/fparser/two/tests/fortran2003/test_usestmt_r1109.py
  src/fparser/two/tests/test_fortran2003.py
  src/fparser/two/tests/utils/test_blockbase.py
  src/fparser/two/tests/utils/test_sequencebase.py
  src/fparser/two/utils.py
Labels: under review

#218 Add support for non-ASCII chars in tostr() method of Char_Literal_Constant (for 217)
  src/fparser/two/Fortran2003.py
  src/fparser/two/tests/fortran2003/test_char_literal_constant_r427.py
Labels: ready for review

#220 fix prefix error (issue #219)
  CHANGELOG.md
  src/fparser/two/Fortran2003.py
  src/fparser/two/tests/fortran2003/test_prefix_r1227.py
  src/fparser/two/tests/test_fortran2003.py
  src/fparser/two/tests/utils/test_sequencebase.py
  src/fparser/two/utils.py
Labels: bug, in progress

#224 Improve fparser2 script (issue #223)
  CHANGELOG.md
  doc/fparser2.rst
  src/fparser/scripts/fparser2.py
  src/fparser/scripts/script_options.py
  src/fparser/two/tests/test_scripts.py
Labels: ready for review
