Repository stfc/fparser, pull requests merged in 2020-01, with the labels that each got.

#206 import fix
  CHANGELOG.md
  src/fparser/two/Fortran2003.py
  src/fparser/two/tests/fortran2003/test_import_stmt_r1209.py
  src/fparser/two/tests/utils/test_wordclsbase.py
  src/fparser/two/utils.py
Labels: ready for review

#227 Support for non-ASCII characters in code (within block structures) for #226
  CHANGELOG.md
  src/fparser/two/Fortran2003.py
  src/fparser/two/tests/fortran2003/test_block_do_construct_r826.py
  src/fparser/two/tests/fortran2003/test_case_construct_r808.py
  src/fparser/two/tests/fortran2003/test_component_part_r438.py
  src/fparser/two/tests/fortran2003/test_if_construct_r802.py
  src/fparser/two/tests/fortran2003/test_nonblock_do_construct_r835.py
  src/fparser/two/tests/fortran2003/test_where_construct_r744.py
  src/fparser/two/tests/test_bases.py
  src/fparser/two/tests/test_fortran2003.py
  src/fparser/two/utils.py
Labels: under review

#233 Statements in multi-statement line not parsed correctly (issue #161)
  CHANGELOG.md
  src/fparser/common/readfortran.py
  src/fparser/common/tests/test_readfortran.py
Labels: under review

#234 Fix 228: space after unnamed END DO
  CHANGELOG.md
  src/fparser/common/base_classes.py
  src/fparser/common/tests/test_base_classes.py
  src/fparser/one/tests/test_do_block_r814.py
  src/fparser/one/tests/test_parsefortran.py
Labels: ready for merge

#235 172 intent bug
  CHANGELOG.md
  src/fparser/two/pattern_tools.py
  src/fparser/two/tests/test_pattern_tools.py
Labels: ready for merge
