Repository stfc/fparser, pull requests merged in 2020-02, with the labels that each got.

#241 Changed number of expected arguments for intrinsic function IBITS to 3
  src/fparser/two/Fortran2003.py
Labels: ready for merge

#240 Some minor contributions to issue #26
  src/fparser/common/utils.py
  src/fparser/two/Fortran2003.py
Labels: ready for review, under review

#238 Element vs Section fix (issue #213)
  CHANGELOG.md
  doc/fparser2.rst
  src/fparser/two/Fortran2003.py
  src/fparser/two/tests/fortran2003/test_designator_r603.py
  src/fparser/two/tests/fortran2003/test_primary_r701.py
Labels: ready for merge, ready for review

#246 #245 Fix python deprecation warnings caused by RE strings.
  CHANGELOG.md
  src/fparser/two/pattern_tools.py
Labels: bug, ready for merge
