Repository stfc/fparser, pull requests merged in 2022-08, with the labels that each got.

#363 #362 Dependency example: support files in subdirectories.
  CHANGELOG.md
  example/README.md
  example/create_dependencies.py
Labels: enhancement, ready for merge

#364 Fix parsing of format-items with hollerith items and omitted commas
  src/fparser/two/Fortran2003.py
  src/fparser/two/tests/fortran2003/test_format_item_list.py
  src/fparser/two/tests/fortran2003/test_format_item_r1003.py
  src/fparser/two/tests/test_fortran2003.py
Labels: reviewed with actions

#368 Add support for visiting tuples in walk() utility
  src/fparser/two/tests/utils/test_walk.py
  src/fparser/two/utils.py
Labels: under review
