Repository stfc/fparser, pull requests merged in 2022-09, with the labels that each got.

#356 (Closes #298) add support for mold and tests
  CHANGELOG.md
  doc/fparser2.rst
  src/fparser/two/Fortran2003.py
  src/fparser/two/Fortran2008.py
  src/fparser/two/tests/fortran2003/test_allocate_stmt_r623.py
  src/fparser/two/tests/fortran2008/test_alloc_opt_r627.py
Labels: ready for merge

#372 Fix trailing whitespace being lost when Format_Item_List is in parentheses
  src/fparser/two/Fortran2003.py
  src/fparser/two/tests/fortran2003/test_format_item_r1003.py
  src/fparser/two/tests/utils/test_bracket_base.py
  src/fparser/two/utils.py
Labels: under review

#374 tostr staticmethod error (closes #373)
  CHANGELOG.md
  src/fparser/two/Fortran2003.py
  src/fparser/two/tests/fortran2003/test_stmt_function_stmt_r1238.py
Labels: bug, ready for merge

#378 Fix for code containing only comments [closes #375]
  CHANGELOG.md
  src/fparser/two/Fortran2003.py
  src/fparser/two/tests/fortran2003/test_program_r201.py
Labels: bug, ready for merge

#376 Fixes #349 - use association bug
  CHANGELOG.md
  doc/developers_guide.rst
  src/fparser/two/Fortran2003.py
  src/fparser/two/symbol_table.py
  src/fparser/two/tests/fortran2003/test_usestmt_r1109.py
  src/fparser/two/tests/test_module_use.py
  src/fparser/two/tests/test_symbol_table.py
Labels: bug, ready for merge
